version: '3.3'

services:
  react-app:
    container_name: rt-cvision-frontend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: Dockerfile
    image: tannousgeagea/tannousgeagea:rt-cvision-frontend
    networks:
      - internal
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file: .env
    volumes:
      - ./rt_cvision_frontend:/app


networks:
  internal:
    driver: bridge 